### PR TITLE
changed trip database to users

### PR DESCRIPTION
**Pull request by gbell76**
Changed the trip database to users and updated database to reflect user requirements

### CODE REVIEW

**Comment by ChairSitter** [comment]
This is good, I notice that the word trip is still in all that commented-out code in the script.js. Probably not too important but I'm not sure if we would want to just delete all the commented-out code or change trip to user there?

**Comment by gbell76** [comment]
Yeah I kept some of the original code which used trip commented out as a template in case I messed something up. When the project is done we'll delete all the comments

**Comment by ChairSitter** [comment]
Ok cool, it looks good then. So do I hit merge pull request, or do you, or is there another step?

**Comment by gbell76** [comment]
I think you merge the pull request

**Pull request merged**
